name: publish

on:
  push:
    branches: [ dev]

jobs:
  publish-image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the Docker image
        run: |
          docker build . -f Dockerfile --tag ghcr.io/sofiasdz/jibber-jabber-ui-dev:latest
          docker push ghcr.io/sofiasdz/jibber-jabber-ui-dev:latest

      - name: Deploy
        uses: fifsky/ssh-action@master
        with:
          command: ~/jj/jibber-jabber-infrastructure/start-jibber-jabber-dev.sh
          host: ${{ secrets.VM_IP_DEV }}
          user: ${{ secrets.VM_USER_DEV }}
          key: ${{ secrets.VM_KEY_DEV }}